### ISSUE TITLE
Tried to build PicatPrism on Arm64 mac os but I can't

### ISSUE THREAD

**Issue by space192** [nfzhou/PicatPrism#1]
![image](https://user-images.githubusercontent.com/44359684/145643467-1ebe00d2-b984-4234-a101-87c213e281ed.png)
Hey so I've tried building the PicatPrism executable for ARM64 mac os, but i can't is there any solution ?

**Comment by nfzhou** [comment]
I have forwarded your email to Picat's news group at:

https://groups.google.com/g/picat-lang/c/58HKkE0aid0

**Comment by space192** [comment]
By replacing clang by the gcc/g++ compiler (installed from homebrew) inside of the makefile I compiled successfully !
